-- سكربت SQL لإنشاء جدول SubscriptionLogs
-- تطبيق على السيرفر VPS مباشرة

-- إنشاء الجدول
CREATE TABLE IF NOT EXISTS "SubscriptionLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- معلومات العميل
    "CustomerId" text NULL,
    "CustomerName" text NULL,
    "PhoneNumber" text NULL,
    
    -- معلومات الاشتراك
    "SubscriptionId" text NULL,
    "PlanName" text NULL,
    "PlanPrice" numeric NULL,
    "CommitmentPeriod" integer NULL,
    "BundleId" text NULL,
    "CurrentStatus" text NULL,
    "DeviceUsername" text NULL,
    
    -- معلومات العملية
    "OperationType" text NULL,
    "ActivatedBy" text NULL,
    "ActivationDate" timestamp with time zone NULL,
    "ActivationTime" text NULL,
    "SessionId" text NULL,
    "LastUpdateDate" timestamp with time zone NULL,
    
    -- معلومات الموقع
    "ZoneId" text NULL,
    "ZoneName" text NULL,
    "FbgInfo" text NULL,
    "FatInfo" text NULL,
    "FdtInfo" text NULL,
    
    -- معلومات المحفظة
    "WalletBalanceBefore" numeric NULL,
    "WalletBalanceAfter" numeric NULL,
    "PartnerWalletBalanceBefore" numeric NULL,
    "CustomerWalletBalanceBefore" numeric NULL,
    "Currency" text NULL,
    "PaymentMethod" text NULL,
    
    -- معلومات الشريك/الموظف
    "PartnerName" text NULL,
    "PartnerId" text NULL,
    "UserId" uuid NULL,
    "CompanyId" uuid NULL,
    
    -- حالة العملية
    "IsPrinted" boolean NOT NULL DEFAULT false,
    "IsWhatsAppSent" boolean NOT NULL DEFAULT false,
    "SubscriptionNotes" text NULL,
    
    -- معلومات إضافية
    "StartDate" text NULL,
    "EndDate" text NULL,
    "ApiResponse" text NULL,
    
    -- BaseEntity fields
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone NULL
);

-- إضافة فهارس للبحث السريع
CREATE INDEX IF NOT EXISTS "IX_SubscriptionLogs_SubscriptionId" ON "SubscriptionLogs" ("SubscriptionId");
CREATE INDEX IF NOT EXISTS "IX_SubscriptionLogs_ZoneId" ON "SubscriptionLogs" ("ZoneId");
CREATE INDEX IF NOT EXISTS "IX_SubscriptionLogs_ActivationDate" ON "SubscriptionLogs" ("ActivationDate");
CREATE INDEX IF NOT EXISTS "IX_SubscriptionLogs_OperationType" ON "SubscriptionLogs" ("OperationType");
CREATE INDEX IF NOT EXISTS "IX_SubscriptionLogs_IsDeleted" ON "SubscriptionLogs" ("IsDeleted");

-- تسجيل الـ Migration في جدول التاريخ
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260206224918_AddSubscriptionLogs', '9.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;

-- التحقق
SELECT 'تم إنشاء جدول SubscriptionLogs بنجاح!' AS "Result";
