-- Migration: AddWhatsAppBatchReports
-- تطبيق يدوي على PostgreSQL (sadara_db)
-- sudo -u postgres psql -d sadara_db -f manual_whatsapp_batch_reports.sql

CREATE TABLE IF NOT EXISTS "WhatsAppBatchReports" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "BatchId" text NOT NULL DEFAULT '',
    "TemplateType" text,
    "Total" integer NOT NULL DEFAULT 0,
    "Sent" integer NOT NULL DEFAULT 0,
    "Failed" integer NOT NULL DEFAULT 0,
    "Rate" text,
    "CompletedAt" timestamp with time zone,
    "Warning" text,
    "FailedSummary" text,
    "EarlyStop" boolean NOT NULL DEFAULT false,
    "EarlyStopReason" text,
    "Status" text NOT NULL DEFAULT 'completed',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_WhatsAppBatchReports" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_WhatsAppBatchReports_BatchId"
    ON "WhatsAppBatchReports" ("BatchId");

-- تسجيل في __EFMigrationsHistory
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260330000000_AddWhatsAppBatchReports', '9.0.0')
ON CONFLICT DO NOTHING;
