-- Migration: AddEmployeeLocations
-- تطبيق يدوي على PostgreSQL (sadara_db)

CREATE TABLE IF NOT EXISTS "EmployeeLocations" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL DEFAULT '',
    "Department" text,
    "Center" text,
    "Phone" text,
    "Latitude" double precision NOT NULL DEFAULT 0,
    "Longitude" double precision NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT true,
    "LastUpdate" timestamp with time zone NOT NULL DEFAULT NOW(),
    "CompanyId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_EmployeeLocations" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_EmployeeLocations_UserId"
    ON "EmployeeLocations" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_EmployeeLocations_IsActive"
    ON "EmployeeLocations" ("IsActive");

-- جدول سجل المواقع التاريخي
CREATE TABLE IF NOT EXISTS "EmployeeLocationLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL DEFAULT '',
    "Latitude" double precision NOT NULL DEFAULT 0,
    "Longitude" double precision NOT NULL DEFAULT 0,
    "RecordedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_EmployeeLocationLogs" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_EmployeeLocationLogs_UserId_RecordedAt"
    ON "EmployeeLocationLogs" ("UserId", "RecordedAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260330000001_AddEmployeeLocations', '9.0.0')
ON CONFLICT DO NOTHING;
