-- Migration: AddReminderTables

CREATE TABLE IF NOT EXISTS "ReminderSettings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" text NOT NULL DEFAULT '',
    "IsEnabled" boolean NOT NULL DEFAULT false,
    "BatchesJson" jsonb NOT NULL DEFAULT '[]',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_ReminderSettings" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ReminderSettings_TenantId"
    ON "ReminderSettings" ("TenantId");

CREATE TABLE IF NOT EXISTS "ReminderExecutionLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" text NOT NULL DEFAULT '',
    "BatchId" text,
    "Days" integer NOT NULL DEFAULT 0,
    "Total" integer NOT NULL DEFAULT 0,
    "Sent" integer NOT NULL DEFAULT 0,
    "Failed" integer NOT NULL DEFAULT 0,
    "ExecutedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "IsManual" boolean NOT NULL DEFAULT false,
    "TriggeredBy" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_ReminderExecutionLogs" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_ReminderExecutionLogs_TenantId_ExecutedAt"
    ON "ReminderExecutionLogs" ("TenantId", "ExecutedAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260331000000_AddReminderTables', '9.0.0')
ON CONFLICT DO NOTHING;
