-- Migration: AddWhatsAppData
-- تطبيق يدوي على PostgreSQL (sadara_db)
-- sudo -u postgres psql -d sadara_db -f manual_whatsapp_tables.sql

-- 1. جدول المحادثات
CREATE TABLE IF NOT EXISTS "WhatsAppConversations" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PhoneNumber" text NOT NULL DEFAULT '',
    "UserName" text,
    "ContactName" text,
    "LastMessage" text NOT NULL DEFAULT '',
    "LastMessageTime" timestamp with time zone NOT NULL DEFAULT NOW(),
    "LastMessageType" text NOT NULL DEFAULT 'text',
    "UnreadCount" integer NOT NULL DEFAULT 0,
    "IsIncoming" boolean NOT NULL DEFAULT false,
    "CompanyId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_WhatsAppConversations" PRIMARY KEY ("Id")
);

-- 2. جدول الرسائل
CREATE TABLE IF NOT EXISTS "WhatsAppMessages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ExternalMessageId" text NOT NULL DEFAULT '',
    "ConversationId" bigint NOT NULL,
    "PhoneNumber" text NOT NULL DEFAULT '',
    "Text" text NOT NULL DEFAULT '',
    "MessageType" text NOT NULL DEFAULT 'text',
    "Direction" text NOT NULL DEFAULT 'incoming',
    "Status" text NOT NULL DEFAULT 'received',
    "ContactName" text,
    "MediaId" text,
    "MediaUrl" text,
    "MimeType" text,
    "MediaFileName" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_WhatsAppMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WhatsAppMessages_WhatsAppConversations_ConversationId"
        FOREIGN KEY ("ConversationId") REFERENCES "WhatsAppConversations" ("Id")
        ON DELETE CASCADE
);

-- 3. Indexes
CREATE UNIQUE INDEX IF NOT EXISTS "IX_WhatsAppConversations_PhoneNumber"
    ON "WhatsAppConversations" ("PhoneNumber");

CREATE INDEX IF NOT EXISTS "IX_WhatsAppConversations_LastMessageTime"
    ON "WhatsAppConversations" ("LastMessageTime");

CREATE INDEX IF NOT EXISTS "IX_WhatsAppMessages_ExternalMessageId"
    ON "WhatsAppMessages" ("ExternalMessageId");

CREATE INDEX IF NOT EXISTS "IX_WhatsAppMessages_ConversationId_CreatedAt"
    ON "WhatsAppMessages" ("ConversationId", "CreatedAt");

-- 4. تسجيل في __EFMigrationsHistory
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260329000000_AddWhatsAppData', '9.0.0')
ON CONFLICT DO NOTHING;
