-- Accounting System Migration
-- Fix Users.Salary from text to numeric(18,2)
ALTER TABLE "Users" ALTER COLUMN "Salary" TYPE numeric(18,2)
    USING CASE WHEN "Salary" IS NULL THEN NULL 
               WHEN "Salary" ~ '^\d+\.?\d*$' THEN "Salary"::numeric(18,2) 
               ELSE 0 END;

-- Add columns to Notifications
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Notifications' AND column_name='CompanyId') THEN
        ALTER TABLE "Notifications" ADD "CompanyId" uuid;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Notifications' AND column_name='ReferenceId') THEN
        ALTER TABLE "Notifications" ADD "ReferenceId" uuid;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Notifications' AND column_name='ReferenceType') THEN
        ALTER TABLE "Notifications" ADD "ReferenceType" text;
    END IF;
END $$;

-- Create Accounts table
CREATE TABLE IF NOT EXISTS "Accounts" (
    "Id" uuid NOT NULL,
    "Code" character varying(50) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "NameEn" character varying(200),
    "AccountType" integer NOT NULL,
    "ParentAccountId" uuid,
    "OpeningBalance" numeric(18,2) NOT NULL DEFAULT 0,
    "CurrentBalance" numeric(18,2) NOT NULL DEFAULT 0,
    "IsSystemAccount" boolean NOT NULL DEFAULT false,
    "Level" integer NOT NULL DEFAULT 0,
    "IsLeaf" boolean NOT NULL DEFAULT true,
    "IsActive" boolean NOT NULL DEFAULT true,
    "Description" character varying(500),
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Accounts_Accounts_ParentAccountId" FOREIGN KEY ("ParentAccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Accounts_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT
);

-- Create JournalEntries table
CREATE TABLE IF NOT EXISTS "JournalEntries" (
    "Id" uuid NOT NULL,
    "EntryNumber" character varying(50) NOT NULL,
    "EntryDate" timestamp with time zone NOT NULL,
    "Description" character varying(500) NOT NULL,
    "TotalDebit" numeric(18,2) NOT NULL DEFAULT 0,
    "TotalCredit" numeric(18,2) NOT NULL DEFAULT 0,
    "ReferenceType" integer NOT NULL DEFAULT 0,
    "ReferenceId" character varying(100),
    "Status" integer NOT NULL DEFAULT 0,
    "Notes" text,
    "CompanyId" uuid NOT NULL,
    "CreatedById" uuid NOT NULL,
    "ApprovedById" uuid,
    "ApprovedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_JournalEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_JournalEntries_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_JournalEntries_Users_ApprovedById" FOREIGN KEY ("ApprovedById") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_JournalEntries_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

-- Create CashBoxes table
CREATE TABLE IF NOT EXISTS "CashBoxes" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "CashBoxType" integer NOT NULL DEFAULT 0,
    "CurrentBalance" numeric(18,2) NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT true,
    "ResponsibleUserId" uuid,
    "CompanyId" uuid NOT NULL,
    "LinkedAccountId" uuid,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_CashBoxes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CashBoxes_Accounts_LinkedAccountId" FOREIGN KEY ("LinkedAccountId") REFERENCES "Accounts" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_CashBoxes_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CashBoxes_Users_ResponsibleUserId" FOREIGN KEY ("ResponsibleUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

-- Create EmployeeSalaries table
CREATE TABLE IF NOT EXISTS "EmployeeSalaries" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "Month" integer NOT NULL,
    "Year" integer NOT NULL,
    "BaseSalary" numeric(18,2) NOT NULL DEFAULT 0,
    "Allowances" numeric(18,2) NOT NULL DEFAULT 0,
    "Deductions" numeric(18,2) NOT NULL DEFAULT 0,
    "Bonuses" numeric(18,2) NOT NULL DEFAULT 0,
    "NetSalary" numeric(18,2) NOT NULL DEFAULT 0,
    "Status" integer NOT NULL DEFAULT 0,
    "PaidAt" timestamp with time zone,
    "JournalEntryId" uuid,
    "Notes" text,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_EmployeeSalaries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmployeeSalaries_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_EmployeeSalaries_JournalEntries_JournalEntryId" FOREIGN KEY ("JournalEntryId") REFERENCES "JournalEntries" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_EmployeeSalaries_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

-- Create JournalEntryLines table
CREATE TABLE IF NOT EXISTS "JournalEntryLines" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "JournalEntryId" uuid NOT NULL,
    "AccountId" uuid NOT NULL,
    "DebitAmount" numeric(18,2) NOT NULL DEFAULT 0,
    "CreditAmount" numeric(18,2) NOT NULL DEFAULT 0,
    "Description" character varying(500),
    "EntityType" character varying(50),
    "EntityId" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_JournalEntryLines" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_JournalEntryLines_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_JournalEntryLines_JournalEntries_JournalEntryId" FOREIGN KEY ("JournalEntryId") REFERENCES "JournalEntries" ("Id") ON DELETE CASCADE
);

-- Create CashTransactions table
CREATE TABLE IF NOT EXISTS "CashTransactions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CashBoxId" uuid NOT NULL,
    "TransactionType" integer NOT NULL DEFAULT 0,
    "Amount" numeric(18,2) NOT NULL DEFAULT 0,
    "BalanceAfter" numeric(18,2) NOT NULL DEFAULT 0,
    "Description" character varying(500) NOT NULL,
    "JournalEntryId" uuid,
    "ReferenceType" integer NOT NULL DEFAULT 0,
    "ReferenceId" character varying(100),
    "CreatedById" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_CashTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CashTransactions_CashBoxes_CashBoxId" FOREIGN KEY ("CashBoxId") REFERENCES "CashBoxes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CashTransactions_JournalEntries_JournalEntryId" FOREIGN KEY ("JournalEntryId") REFERENCES "JournalEntries" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_CashTransactions_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

-- Create Expenses table
CREATE TABLE IF NOT EXISTS "Expenses" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AccountId" uuid NOT NULL,
    "Amount" numeric(18,2) NOT NULL DEFAULT 0,
    "Description" character varying(500) NOT NULL,
    "ExpenseDate" timestamp with time zone NOT NULL,
    "Category" character varying(100),
    "JournalEntryId" uuid,
    "PaidFromCashBoxId" uuid,
    "CreatedById" uuid NOT NULL,
    "AttachmentUrl" character varying(500),
    "Notes" text,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Expenses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Expenses_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Expenses_CashBoxes_PaidFromCashBoxId" FOREIGN KEY ("PaidFromCashBoxId") REFERENCES "CashBoxes" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Expenses_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Expenses_JournalEntries_JournalEntryId" FOREIGN KEY ("JournalEntryId") REFERENCES "JournalEntries" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Expenses_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

-- Create TechnicianCollections table
CREATE TABLE IF NOT EXISTS "TechnicianCollections" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TechnicianId" uuid NOT NULL,
    "CitizenId" uuid,
    "ServiceRequestId" uuid,
    "Amount" numeric(18,2) NOT NULL DEFAULT 0,
    "CollectionDate" timestamp with time zone NOT NULL,
    "IsDelivered" boolean NOT NULL DEFAULT false,
    "DeliveredAt" timestamp with time zone,
    "DeliveredToUserId" uuid,
    "JournalEntryId" uuid,
    "CashBoxId" uuid,
    "Notes" text,
    "Description" character varying(500),
    "PaymentMethod" integer NOT NULL DEFAULT 0,
    "ReceiptNumber" character varying(100),
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_TechnicianCollections" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TechnicianCollections_CashBoxes_CashBoxId" FOREIGN KEY ("CashBoxId") REFERENCES "CashBoxes" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_TechnicianCollections_Citizens_CitizenId" FOREIGN KEY ("CitizenId") REFERENCES "Citizens" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_TechnicianCollections_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TechnicianCollections_JournalEntries_JournalEntryId" FOREIGN KEY ("JournalEntryId") REFERENCES "JournalEntries" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_TechnicianCollections_ServiceRequests_ServiceRequestId" FOREIGN KEY ("ServiceRequestId") REFERENCES "ServiceRequests" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_TechnicianCollections_Users_DeliveredToUserId" FOREIGN KEY ("DeliveredToUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_TechnicianCollections_Users_TechnicianId" FOREIGN KEY ("TechnicianId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

-- Create Indexes
CREATE INDEX IF NOT EXISTS "IX_Accounts_AccountType" ON "Accounts" ("AccountType");
CREATE INDEX IF NOT EXISTS "IX_Accounts_CompanyId" ON "Accounts" ("CompanyId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Accounts_CompanyId_Code" ON "Accounts" ("CompanyId", "Code");
CREATE INDEX IF NOT EXISTS "IX_Accounts_ParentAccountId" ON "Accounts" ("ParentAccountId");

CREATE INDEX IF NOT EXISTS "IX_CashBoxes_CompanyId" ON "CashBoxes" ("CompanyId");
CREATE INDEX IF NOT EXISTS "IX_CashBoxes_LinkedAccountId" ON "CashBoxes" ("LinkedAccountId");
CREATE INDEX IF NOT EXISTS "IX_CashBoxes_ResponsibleUserId" ON "CashBoxes" ("ResponsibleUserId");

CREATE INDEX IF NOT EXISTS "IX_CashTransactions_CashBoxId" ON "CashTransactions" ("CashBoxId");
CREATE INDEX IF NOT EXISTS "IX_CashTransactions_CreatedAt" ON "CashTransactions" ("CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_CashTransactions_CreatedById" ON "CashTransactions" ("CreatedById");
CREATE INDEX IF NOT EXISTS "IX_CashTransactions_JournalEntryId" ON "CashTransactions" ("JournalEntryId");

CREATE INDEX IF NOT EXISTS "IX_EmployeeSalaries_CompanyId" ON "EmployeeSalaries" ("CompanyId");
CREATE INDEX IF NOT EXISTS "IX_EmployeeSalaries_JournalEntryId" ON "EmployeeSalaries" ("JournalEntryId");
CREATE INDEX IF NOT EXISTS "IX_EmployeeSalaries_Status" ON "EmployeeSalaries" ("Status");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_EmployeeSalaries_UserId_Year_Month" ON "EmployeeSalaries" ("UserId", "Year", "Month");

CREATE INDEX IF NOT EXISTS "IX_Expenses_AccountId" ON "Expenses" ("AccountId");
CREATE INDEX IF NOT EXISTS "IX_Expenses_CompanyId" ON "Expenses" ("CompanyId");
CREATE INDEX IF NOT EXISTS "IX_Expenses_CreatedById" ON "Expenses" ("CreatedById");
CREATE INDEX IF NOT EXISTS "IX_Expenses_ExpenseDate" ON "Expenses" ("ExpenseDate");
CREATE INDEX IF NOT EXISTS "IX_Expenses_JournalEntryId" ON "Expenses" ("JournalEntryId");
CREATE INDEX IF NOT EXISTS "IX_Expenses_PaidFromCashBoxId" ON "Expenses" ("PaidFromCashBoxId");

CREATE INDEX IF NOT EXISTS "IX_JournalEntries_ApprovedById" ON "JournalEntries" ("ApprovedById");
CREATE INDEX IF NOT EXISTS "IX_JournalEntries_CompanyId" ON "JournalEntries" ("CompanyId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_JournalEntries_CompanyId_EntryNumber" ON "JournalEntries" ("CompanyId", "EntryNumber");
CREATE INDEX IF NOT EXISTS "IX_JournalEntries_CreatedById" ON "JournalEntries" ("CreatedById");
CREATE INDEX IF NOT EXISTS "IX_JournalEntries_EntryDate" ON "JournalEntries" ("EntryDate");
CREATE INDEX IF NOT EXISTS "IX_JournalEntries_ReferenceType" ON "JournalEntries" ("ReferenceType");
CREATE INDEX IF NOT EXISTS "IX_JournalEntries_Status" ON "JournalEntries" ("Status");

CREATE INDEX IF NOT EXISTS "IX_JournalEntryLines_AccountId" ON "JournalEntryLines" ("AccountId");
CREATE INDEX IF NOT EXISTS "IX_JournalEntryLines_JournalEntryId" ON "JournalEntryLines" ("JournalEntryId");

CREATE INDEX IF NOT EXISTS "IX_TechnicianCollections_CashBoxId" ON "TechnicianCollections" ("CashBoxId");
CREATE INDEX IF NOT EXISTS "IX_TechnicianCollections_CitizenId" ON "TechnicianCollections" ("CitizenId");
CREATE INDEX IF NOT EXISTS "IX_TechnicianCollections_CollectionDate" ON "TechnicianCollections" ("CollectionDate");
CREATE INDEX IF NOT EXISTS "IX_TechnicianCollections_CompanyId" ON "TechnicianCollections" ("CompanyId");
CREATE INDEX IF NOT EXISTS "IX_TechnicianCollections_DeliveredToUserId" ON "TechnicianCollections" ("DeliveredToUserId");
CREATE INDEX IF NOT EXISTS "IX_TechnicianCollections_IsDelivered" ON "TechnicianCollections" ("IsDelivered");
CREATE INDEX IF NOT EXISTS "IX_TechnicianCollections_JournalEntryId" ON "TechnicianCollections" ("JournalEntryId");
CREATE INDEX IF NOT EXISTS "IX_TechnicianCollections_ServiceRequestId" ON "TechnicianCollections" ("ServiceRequestId");
CREATE INDEX IF NOT EXISTS "IX_TechnicianCollections_TechnicianId" ON "TechnicianCollections" ("TechnicianId");

-- Record the migration
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260217093425_AddAccountingSystem', '9.0.2');
