CREATE TABLE IF NOT EXISTS "TaskAudits" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ServiceRequestId" uuid NOT NULL,
    "RequestNumber" text,
    "AuditStatus" text NOT NULL,
    "Rating" integer NOT NULL,
    "Notes" text,
    "AuditedBy" text,
    "AuditedAt" timestamp with time zone,
    "CompanyId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_TaskAudits" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260218200849_AddTaskAudit', '9.0.2'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218200849_AddTaskAudit');
