#!/bin/bash
export PGPASSWORD=sadara_secure_password_2024

# Check if tables exist
echo "=== Checking existing tables ==="
psql -h 127.0.0.1 -U sadara_user -d sadara_db -t -A -c "SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_name LIKE 'Dep%';"

echo "=== Creating tables ==="
psql -h 127.0.0.1 -U sadara_user -d sadara_db <<'EOSQL'
CREATE TABLE IF NOT EXISTS "Departments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NameAr" character varying(100) NOT NULL,
    "Name" character varying(100),
    "CompanyId" uuid NOT NULL,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Departments_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "DepartmentTasks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NameAr" character varying(100) NOT NULL,
    "Name" character varying(100),
    "DepartmentId" integer NOT NULL,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_DepartmentTasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DepartmentTasks_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Departments_CompanyId" ON "Departments" ("CompanyId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Departments_CompanyId_NameAr" ON "Departments" ("CompanyId", "NameAr");
CREATE INDEX IF NOT EXISTS "IX_DepartmentTasks_DepartmentId" ON "DepartmentTasks" ("DepartmentId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_DepartmentTasks_DepartmentId_NameAr" ON "DepartmentTasks" ("DepartmentId", "NameAr");
EOSQL

echo "=== Verifying ==="
psql -h 127.0.0.1 -U sadara_user -d sadara_db -t -A -c "SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_name LIKE 'Dep%';"
echo "=== Done ==="
