-- Create FixedExpenses table
CREATE TABLE IF NOT EXISTS "FixedExpenses" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Category" integer NOT NULL,
    "MonthlyAmount" numeric NOT NULL,
    "Description" text,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_FixedExpenses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FixedExpenses_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

-- Create FixedExpensePayments table
CREATE TABLE IF NOT EXISTS "FixedExpensePayments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FixedExpenseId" bigint NOT NULL,
    "Month" integer NOT NULL,
    "Year" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "IsPaid" boolean NOT NULL DEFAULT false,
    "PaidAt" timestamp with time zone,
    "JournalEntryId" uuid,
    "Notes" text,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_FixedExpensePayments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FixedExpensePayments_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_FixedExpensePayments_FixedExpenses_FixedExpenseId" FOREIGN KEY ("FixedExpenseId") REFERENCES "FixedExpenses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_FixedExpensePayments_JournalEntries_JournalEntryId" FOREIGN KEY ("JournalEntryId") REFERENCES "JournalEntries" ("Id")
);

-- Create indexes
CREATE INDEX IF NOT EXISTS "IX_FixedExpensePayments_CompanyId" ON "FixedExpensePayments" ("CompanyId");
CREATE INDEX IF NOT EXISTS "IX_FixedExpensePayments_FixedExpenseId" ON "FixedExpensePayments" ("FixedExpenseId");
CREATE INDEX IF NOT EXISTS "IX_FixedExpensePayments_JournalEntryId" ON "FixedExpensePayments" ("JournalEntryId");
CREATE INDEX IF NOT EXISTS "IX_FixedExpenses_CompanyId" ON "FixedExpenses" ("CompanyId");

-- Record migration
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260222035816_AddFixedExpenses', '9.0.2'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260222035816_AddFixedExpenses');
