ALTER TABLE "Users" ALTER COLUMN "DateOfBirth" TYPE TIMESTAMPTZ USING "DateOfBirth" AT TIME ZONE 'UTC';
ALTER TABLE "Users" ALTER COLUMN "HireDate" TYPE TIMESTAMPTZ USING "HireDate" AT TIME ZONE 'UTC';
