-- Migration: AddTechnicianTransactions
-- Add technician financial fields to Users
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TechNetBalance" numeric NOT NULL DEFAULT 0;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TechTotalCharges" numeric NOT NULL DEFAULT 0;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TechTotalPayments" numeric NOT NULL DEFAULT 0;

-- Create TechnicianTransactions table
CREATE TABLE IF NOT EXISTS "TechnicianTransactions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TechnicianId" uuid NOT NULL,
    "Type" integer NOT NULL,
    "Category" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "BalanceAfter" numeric NOT NULL,
    "Description" text NOT NULL,
    "ReferenceNumber" text,
    "ServiceRequestId" uuid,
    "CreatedById" uuid,
    "Notes" text,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_TechnicianTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TechnicianTransactions_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TechnicianTransactions_ServiceRequests_ServiceRequestId" FOREIGN KEY ("ServiceRequestId") REFERENCES "ServiceRequests"("Id"),
    CONSTRAINT "FK_TechnicianTransactions_Users_TechnicianId" FOREIGN KEY ("TechnicianId") REFERENCES "Users"("Id") ON DELETE CASCADE
);

-- Create indexes
CREATE INDEX IF NOT EXISTS "IX_TechnicianTransactions_CompanyId" ON "TechnicianTransactions" ("CompanyId");
CREATE INDEX IF NOT EXISTS "IX_TechnicianTransactions_ServiceRequestId" ON "TechnicianTransactions" ("ServiceRequestId");
CREATE INDEX IF NOT EXISTS "IX_TechnicianTransactions_TechnicianId" ON "TechnicianTransactions" ("TechnicianId");
