START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218200849_AddTaskAudit') THEN
    ALTER TABLE "ServiceRequests" ADD "InternetPlanId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218200849_AddTaskAudit') THEN
    ALTER TABLE "InternetPlans" ADD "ProfitAmount" numeric(18,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218200849_AddTaskAudit') THEN
    CREATE TABLE "AgentCommissionRates" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "AgentId" uuid NOT NULL,
        "InternetPlanId" uuid NOT NULL,
        "CommissionPercentage" numeric(5,2) NOT NULL,
        "CompanyId" uuid NOT NULL,
        "IsActive" boolean NOT NULL,
        "Notes" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_AgentCommissionRates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AgentCommissionRates_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AgentCommissionRates_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_AgentCommissionRates_InternetPlans_InternetPlanId" FOREIGN KEY ("InternetPlanId") REFERENCES "InternetPlans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218200849_AddTaskAudit') THEN
    CREATE TABLE "TaskAudits" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ServiceRequestId" uuid NOT NULL,
        "RequestNumber" text,
        "AuditStatus" text NOT NULL,
        "Rating" integer NOT NULL,
        "Notes" text,
        "AuditedBy" text,
        "AuditedAt" timestamp with time zone,
        "CompanyId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_TaskAudits" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218200849_AddTaskAudit') THEN
    CREATE INDEX "IX_ServiceRequests_InternetPlanId" ON "ServiceRequests" ("InternetPlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218200849_AddTaskAudit') THEN
    CREATE UNIQUE INDEX "IX_AgentCommissionRates_AgentId_InternetPlanId" ON "AgentCommissionRates" ("AgentId", "InternetPlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218200849_AddTaskAudit') THEN
    CREATE INDEX "IX_AgentCommissionRates_CompanyId" ON "AgentCommissionRates" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218200849_AddTaskAudit') THEN
    CREATE INDEX "IX_AgentCommissionRates_InternetPlanId" ON "AgentCommissionRates" ("InternetPlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218200849_AddTaskAudit') THEN
    ALTER TABLE "ServiceRequests" ADD CONSTRAINT "FK_ServiceRequests_InternetPlans_InternetPlanId" FOREIGN KEY ("InternetPlanId") REFERENCES "InternetPlans" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218200849_AddTaskAudit') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260218200849_AddTaskAudit', '9.0.2');
    END IF;
END $EF$;
COMMIT;

