START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    ALTER TABLE "ServiceRequests" DROP CONSTRAINT "FK_ServiceRequests_Citizens_CitizenId1";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    ALTER TABLE "ServiceRequests" DROP CONSTRAINT "FK_ServiceRequests_Users_CitizenId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    ALTER TABLE "ServiceRequestStatusHistories" DROP CONSTRAINT "FK_ServiceRequestStatusHistories_Users_ChangedById";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    DROP INDEX "IX_ServiceRequests_CitizenId1";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    ALTER TABLE "ServiceRequests" DROP COLUMN "CitizenId1";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    ALTER TABLE "SubscriptionLogs" ADD "PaymentStatus" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    ALTER TABLE "SubscriptionLogs" ADD "TechnicianName" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    ALTER TABLE "ServiceRequestStatusHistories" ALTER COLUMN "ChangedById" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    ALTER TABLE "ServiceRequests" ALTER COLUMN "CitizenId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    ALTER TABLE "ServiceRequests" ADD "AgentId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    CREATE TABLE "AttendanceRecords" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "UserName" text NOT NULL,
        "CompanyId" uuid,
        "Date" date NOT NULL,
        "CheckInTime" timestamp with time zone,
        "CheckOutTime" timestamp with time zone,
        "CenterName" text,
        "CheckInLatitude" double precision,
        "CheckInLongitude" double precision,
        "CheckOutLatitude" double precision,
        "CheckOutLongitude" double precision,
        "SecurityCode" text,
        "Notes" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_AttendanceRecords" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AttendanceRecords_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    CREATE TABLE "ISPSubscribers" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Region" text,
        "Agent" text,
        "Dash" text,
        "MotherName" text,
        "PhoneNumber" text,
        "CompanyId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_ISPSubscribers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    CREATE TABLE "WorkCenters" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Latitude" double precision NOT NULL,
        "Longitude" double precision NOT NULL,
        "RadiusMeters" double precision NOT NULL,
        "CompanyId" uuid,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_WorkCenters" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    CREATE TABLE "ZoneStatistics" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ZoneName" text NOT NULL,
        "Fats" integer NOT NULL,
        "TotalUsers" integer NOT NULL,
        "ActiveUsers" integer NOT NULL,
        "InactiveUsers" integer NOT NULL,
        "RegionName" text,
        "CompanyId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_ZoneStatistics" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    CREATE INDEX "IX_ServiceRequests_AgentId" ON "ServiceRequests" ("AgentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    CREATE INDEX "IX_AttendanceRecords_UserId" ON "AttendanceRecords" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    ALTER TABLE "ServiceRequests" ADD CONSTRAINT "FK_ServiceRequests_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    ALTER TABLE "ServiceRequests" ADD CONSTRAINT "FK_ServiceRequests_Users_CitizenId" FOREIGN KEY ("CitizenId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    ALTER TABLE "ServiceRequestStatusHistories" ADD CONSTRAINT "FK_ServiceRequestStatusHistories_Users_ChangedById" FOREIGN KEY ("ChangedById") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities', '9.0.2');
    END IF;
END $EF$;
COMMIT;

