-- Safe migration: AddAttendanceISPSubscriberZoneStatisticEntities
-- Handles missing constraints gracefully

BEGIN;

-- Check if already applied
DO $$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities') THEN
        RAISE EXCEPTION 'Migration already applied';
    END IF;
END $$;

-- Drop FK constraints only if they exist
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_ServiceRequests_Citizens_CitizenId1' AND table_name = 'ServiceRequests') THEN
        ALTER TABLE "ServiceRequests" DROP CONSTRAINT "FK_ServiceRequests_Citizens_CitizenId1";
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_ServiceRequests_Users_CitizenId' AND table_name = 'ServiceRequests') THEN
        ALTER TABLE "ServiceRequests" DROP CONSTRAINT "FK_ServiceRequests_Users_CitizenId";
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_ServiceRequestStatusHistories_Users_ChangedById' AND table_name = 'ServiceRequestStatusHistories') THEN
        ALTER TABLE "ServiceRequestStatusHistories" DROP CONSTRAINT "FK_ServiceRequestStatusHistories_Users_ChangedById";
    END IF;
END $$;

-- Drop index if exists
DROP INDEX IF EXISTS "IX_ServiceRequests_CitizenId1";

-- Drop column if exists
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ServiceRequests' AND column_name = 'CitizenId1') THEN
        ALTER TABLE "ServiceRequests" DROP COLUMN "CitizenId1";
    END IF;
END $$;

-- Add new columns to SubscriptionLogs if not exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'SubscriptionLogs' AND column_name = 'PaymentStatus') THEN
        ALTER TABLE "SubscriptionLogs" ADD "PaymentStatus" text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'SubscriptionLogs' AND column_name = 'TechnicianName') THEN
        ALTER TABLE "SubscriptionLogs" ADD "TechnicianName" text;
    END IF;
END $$;

-- Make ChangedById nullable if not already
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ServiceRequestStatusHistories' AND column_name = 'ChangedById' AND is_nullable = 'NO') THEN
        ALTER TABLE "ServiceRequestStatusHistories" ALTER COLUMN "ChangedById" DROP NOT NULL;
    END IF;
END $$;

-- Make CitizenId nullable if not already
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ServiceRequests' AND column_name = 'CitizenId' AND is_nullable = 'NO') THEN
        ALTER TABLE "ServiceRequests" ALTER COLUMN "CitizenId" DROP NOT NULL;
    END IF;
END $$;

-- Add AgentId column if not exists
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ServiceRequests' AND column_name = 'AgentId') THEN
        ALTER TABLE "ServiceRequests" ADD "AgentId" uuid;
    END IF;
END $$;

-- Create 4 new tables
CREATE TABLE IF NOT EXISTS "AttendanceRecords" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "UserName" text NOT NULL,
    "CompanyId" uuid,
    "Date" date NOT NULL,
    "CheckInTime" timestamp with time zone,
    "CheckOutTime" timestamp with time zone,
    "CenterName" text,
    "CheckInLatitude" double precision,
    "CheckInLongitude" double precision,
    "CheckOutLatitude" double precision,
    "CheckOutLongitude" double precision,
    "SecurityCode" text,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_AttendanceRecords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AttendanceRecords_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ISPSubscribers" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Region" text,
    "Agent" text,
    "Dash" text,
    "MotherName" text,
    "PhoneNumber" text,
    "CompanyId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_ISPSubscribers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "WorkCenters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "RadiusMeters" double precision NOT NULL,
    "CompanyId" uuid,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_WorkCenters" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "ZoneStatistics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ZoneName" text NOT NULL,
    "Fats" integer NOT NULL,
    "TotalUsers" integer NOT NULL,
    "ActiveUsers" integer NOT NULL,
    "InactiveUsers" integer NOT NULL,
    "RegionName" text,
    "CompanyId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_ZoneStatistics" PRIMARY KEY ("Id")
);

-- Create indexes
CREATE INDEX IF NOT EXISTS "IX_ServiceRequests_AgentId" ON "ServiceRequests" ("AgentId");
CREATE INDEX IF NOT EXISTS "IX_AttendanceRecords_UserId" ON "AttendanceRecords" ("UserId");

-- Add FK constraints (only if not exist)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_ServiceRequests_Agents_AgentId') THEN
        ALTER TABLE "ServiceRequests" ADD CONSTRAINT "FK_ServiceRequests_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_ServiceRequests_Users_CitizenId') THEN
        ALTER TABLE "ServiceRequests" ADD CONSTRAINT "FK_ServiceRequests_Users_CitizenId" FOREIGN KEY ("CitizenId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_ServiceRequestStatusHistories_Users_ChangedById') THEN
        ALTER TABLE "ServiceRequestStatusHistories" ADD CONSTRAINT "FK_ServiceRequestStatusHistories_Users_ChangedById" FOREIGN KEY ("ChangedById") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

-- Record migration
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260216172537_AddAttendanceISPSubscriberZoneStatisticEntities', '9.0.2');

COMMIT;
