-- ============================================================
-- Safe Migration Script for Sadara Platform
-- Registers already-applied migrations (1-7) and applies new ones (8-10)
-- Generated: 2026-02-22
-- ============================================================

BEGIN;

-- ============================================================
-- PART 1: Register already-applied migrations in history
-- (These were applied via manual SQL scripts before)
-- ============================================================

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260219014615_AddTechnicianTransactions', '9.0.2'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219014615_AddTechnicianTransactions');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260219182207_AddReceivedByToCollection', '9.0.2'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219182207_AddReceivedByToCollection');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260219185709_AddReceivedByToTechnicianTransaction', '9.0.2'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219185709_AddReceivedByToTechnicianTransaction');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260220153919_AddLinkedTechnicianId', '9.0.2'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220153919_AddLinkedTechnicianId');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260221050013_AddRenewalCycleFields', '9.0.2'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221050013_AddRenewalCycleFields');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260221175730_AddHrFieldsToUser', '9.0.2'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221175730_AddHrFieldsToUser');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260221193028_AddDepartmentsAndTasks', '9.0.2'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221193028_AddDepartmentsAndTasks');

COMMIT;

-- ============================================================
-- PART 2: Migration 8 - AddAttendanceSecurityLayers
-- WorkCenters.Description already exists - skip it
-- ============================================================
BEGIN;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221223912_AddAttendanceSecurityLayers') THEN

        -- Add RegisteredDeviceFingerprint to Users
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Users' AND column_name='RegisteredDeviceFingerprint') THEN
            ALTER TABLE "Users" ADD "RegisteredDeviceFingerprint" text;
        END IF;

        -- Add DeviceFingerprint to AttendanceRecords
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='AttendanceRecords' AND column_name='DeviceFingerprint') THEN
            ALTER TABLE "AttendanceRecords" ADD "DeviceFingerprint" text;
        END IF;

        -- Add Description to WorkCenters (may already exist)
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='WorkCenters' AND column_name='Description') THEN
            ALTER TABLE "WorkCenters" ADD "Description" text;
        END IF;

        -- Create AttendanceAuditLogs table
        IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='AttendanceAuditLogs') THEN
            CREATE TABLE "AttendanceAuditLogs" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                "UserId" uuid NOT NULL,
                "UserName" text NOT NULL,
                "CompanyId" uuid,
                "ActionType" text NOT NULL,
                "IsSuccess" boolean NOT NULL,
                "RejectionReason" text,
                "Latitude" double precision,
                "Longitude" double precision,
                "DistanceFromCenter" double precision,
                "CenterName" text,
                "DeviceFingerprint" text,
                "RegisteredDeviceFingerprint" text,
                "IpAddress" text,
                "AttemptTime" timestamp with time zone NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone,
                "IsDeleted" boolean NOT NULL,
                "DeletedAt" timestamp with time zone,
                CONSTRAINT "PK_AttendanceAuditLogs" PRIMARY KEY ("Id")
            );
        END IF;

        -- Create index on WorkCenters.CompanyId (if not exists)
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='IX_WorkCenters_CompanyId') THEN
            CREATE INDEX "IX_WorkCenters_CompanyId" ON "WorkCenters" ("CompanyId");
        END IF;

        -- Add FK on WorkCenters.CompanyId -> Companies.Id (if not exists)
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name='FK_WorkCenters_Companies_CompanyId') THEN
            ALTER TABLE "WorkCenters" ADD CONSTRAINT "FK_WorkCenters_Companies_CompanyId"
                FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id");
        END IF;

        -- Record migration
        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20260221223912_AddAttendanceSecurityLayers', '9.0.2');

    END IF;
END $$;

COMMIT;

-- ============================================================
-- PART 3: Migration 9 - AddWorkSchedulesAndAttendanceStatus
-- ============================================================
BEGIN;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221224831_AddWorkSchedulesAndAttendanceStatus') THEN

        -- Create WorkSchedules table
        IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='WorkSchedules') THEN
            CREATE TABLE "WorkSchedules" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "Name" text NOT NULL,
                "CompanyId" uuid,
                "CenterName" text,
                "DayOfWeek" integer,
                "WorkStartTime" time without time zone NOT NULL,
                "WorkEndTime" time without time zone NOT NULL,
                "LateGraceMinutes" integer NOT NULL,
                "EarlyDepartureThresholdMinutes" integer NOT NULL,
                "IsDefault" boolean NOT NULL,
                "IsActive" boolean NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone,
                "IsDeleted" boolean NOT NULL,
                "DeletedAt" timestamp with time zone,
                CONSTRAINT "PK_WorkSchedules" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_WorkSchedules_Companies_CompanyId"
                    FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id")
            );
        END IF;

        -- Add columns to AttendanceRecords
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='AttendanceRecords' AND column_name='Status') THEN
            ALTER TABLE "AttendanceRecords" ADD "Status" integer NOT NULL DEFAULT 0;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='AttendanceRecords' AND column_name='LateMinutes') THEN
            ALTER TABLE "AttendanceRecords" ADD "LateMinutes" integer;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='AttendanceRecords' AND column_name='WorkedMinutes') THEN
            ALTER TABLE "AttendanceRecords" ADD "WorkedMinutes" integer;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='AttendanceRecords' AND column_name='OvertimeMinutes') THEN
            ALTER TABLE "AttendanceRecords" ADD "OvertimeMinutes" integer;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='AttendanceRecords' AND column_name='EarlyDepartureMinutes') THEN
            ALTER TABLE "AttendanceRecords" ADD "EarlyDepartureMinutes" integer;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='AttendanceRecords' AND column_name='ExpectedStartTime') THEN
            ALTER TABLE "AttendanceRecords" ADD "ExpectedStartTime" time without time zone;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='AttendanceRecords' AND column_name='ExpectedEndTime') THEN
            ALTER TABLE "AttendanceRecords" ADD "ExpectedEndTime" time without time zone;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='AttendanceRecords' AND column_name='WorkScheduleId') THEN
            ALTER TABLE "AttendanceRecords" ADD "WorkScheduleId" integer;
        END IF;

        -- Create indexes
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='IX_AttendanceRecords_WorkScheduleId') THEN
            CREATE INDEX "IX_AttendanceRecords_WorkScheduleId" ON "AttendanceRecords" ("WorkScheduleId");
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='IX_WorkSchedules_CompanyId') THEN
            CREATE INDEX "IX_WorkSchedules_CompanyId" ON "WorkSchedules" ("CompanyId");
        END IF;

        -- Add FK AttendanceRecords -> WorkSchedules
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name='FK_AttendanceRecords_WorkSchedules_WorkScheduleId') THEN
            ALTER TABLE "AttendanceRecords" ADD CONSTRAINT "FK_AttendanceRecords_WorkSchedules_WorkScheduleId"
                FOREIGN KEY ("WorkScheduleId") REFERENCES "WorkSchedules" ("Id") ON DELETE SET NULL;
        END IF;

        -- Record migration
        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20260221224831_AddWorkSchedulesAndAttendanceStatus', '9.0.2');

    END IF;
END $$;

COMMIT;

-- ============================================================
-- PART 4: Migration 10 - AddLeaveManagement
-- ============================================================
BEGIN;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221230352_AddLeaveManagement') THEN

        -- Create LeaveBalances table
        IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='LeaveBalances') THEN
            CREATE TABLE "LeaveBalances" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                "UserId" uuid NOT NULL,
                "CompanyId" uuid,
                "Year" integer NOT NULL,
                "LeaveType" integer NOT NULL,
                "TotalAllowance" integer NOT NULL,
                "UsedDays" integer NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone,
                "IsDeleted" boolean NOT NULL,
                "DeletedAt" timestamp with time zone,
                CONSTRAINT "PK_LeaveBalances" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_LeaveBalances_Users_UserId"
                    FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );
        END IF;

        -- Create LeaveRequests table
        IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='LeaveRequests') THEN
            CREATE TABLE "LeaveRequests" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                "UserId" uuid NOT NULL,
                "UserName" text NOT NULL,
                "CompanyId" uuid,
                "LeaveType" integer NOT NULL,
                "StartDate" date NOT NULL,
                "EndDate" date NOT NULL,
                "TotalDays" integer NOT NULL,
                "Reason" text,
                "Status" integer NOT NULL DEFAULT 0,
                "ReviewedByUserId" uuid,
                "ReviewedByUserName" text,
                "ReviewedAt" timestamp with time zone,
                "ReviewNotes" text,
                "AttachmentUrl" text,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone,
                "IsDeleted" boolean NOT NULL,
                "DeletedAt" timestamp with time zone,
                CONSTRAINT "PK_LeaveRequests" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_LeaveRequests_Users_UserId"
                    FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );
        END IF;

        -- Create indexes
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='IX_LeaveBalances_UserId') THEN
            CREATE INDEX "IX_LeaveBalances_UserId" ON "LeaveBalances" ("UserId");
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='IX_LeaveRequests_UserId') THEN
            CREATE INDEX "IX_LeaveRequests_UserId" ON "LeaveRequests" ("UserId");
        END IF;

        -- Record migration
        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20260221230352_AddLeaveManagement', '9.0.2');

    END IF;
END $$;

COMMIT;

-- ============================================================
-- Verify: show all migrations
-- ============================================================
SELECT "MigrationId" FROM "__EFMigrationsHistory" ORDER BY 1;
