-- Migration: AddSalaryPolicyAndAttendanceDetails
-- Date: 2026-02-22
-- Description: Add attendance detail columns to EmployeeSalaries + create SalaryPolicies table

BEGIN;

-- 1) Add attendance detail columns to EmployeeSalaries (idempotent)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='EmployeeSalaries' AND column_name='AttendanceDays') THEN
        ALTER TABLE "EmployeeSalaries" ADD COLUMN "AttendanceDays" integer NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='EmployeeSalaries' AND column_name='AbsentDays') THEN
        ALTER TABLE "EmployeeSalaries" ADD COLUMN "AbsentDays" integer NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='EmployeeSalaries' AND column_name='TotalLateMinutes') THEN
        ALTER TABLE "EmployeeSalaries" ADD COLUMN "TotalLateMinutes" integer NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='EmployeeSalaries' AND column_name='TotalOvertimeMinutes') THEN
        ALTER TABLE "EmployeeSalaries" ADD COLUMN "TotalOvertimeMinutes" integer NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='EmployeeSalaries' AND column_name='TotalEarlyDepartureMinutes') THEN
        ALTER TABLE "EmployeeSalaries" ADD COLUMN "TotalEarlyDepartureMinutes" integer NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='EmployeeSalaries' AND column_name='UnpaidLeaveDays') THEN
        ALTER TABLE "EmployeeSalaries" ADD COLUMN "UnpaidLeaveDays" integer NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='EmployeeSalaries' AND column_name='PaidLeaveDays') THEN
        ALTER TABLE "EmployeeSalaries" ADD COLUMN "PaidLeaveDays" integer NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='EmployeeSalaries' AND column_name='LateDeduction') THEN
        ALTER TABLE "EmployeeSalaries" ADD COLUMN "LateDeduction" numeric(18,2) NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='EmployeeSalaries' AND column_name='AbsentDeduction') THEN
        ALTER TABLE "EmployeeSalaries" ADD COLUMN "AbsentDeduction" numeric(18,2) NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='EmployeeSalaries' AND column_name='EarlyDepartureDeduction') THEN
        ALTER TABLE "EmployeeSalaries" ADD COLUMN "EarlyDepartureDeduction" numeric(18,2) NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='EmployeeSalaries' AND column_name='UnpaidLeaveDeduction') THEN
        ALTER TABLE "EmployeeSalaries" ADD COLUMN "UnpaidLeaveDeduction" numeric(18,2) NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='EmployeeSalaries' AND column_name='OvertimeBonus') THEN
        ALTER TABLE "EmployeeSalaries" ADD COLUMN "OvertimeBonus" numeric(18,2) NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='EmployeeSalaries' AND column_name='ExpectedWorkDays') THEN
        ALTER TABLE "EmployeeSalaries" ADD COLUMN "ExpectedWorkDays" integer NOT NULL DEFAULT 0;
    END IF;
END $$;

-- 2) Create SalaryPolicies table (idempotent)
CREATE TABLE IF NOT EXISTS "SalaryPolicies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "IsDefault" boolean NOT NULL DEFAULT true,
    "DeductionPerLateMinute" numeric(18,4) NOT NULL DEFAULT 0,
    "MaxLateDeductionPercent" numeric(5,2) NOT NULL DEFAULT 25,
    "AbsentDayMultiplier" numeric(5,2) NOT NULL DEFAULT 1,
    "DeductionPerEarlyDepartureMinute" numeric(18,4) NOT NULL DEFAULT 0,
    "OvertimeHourlyMultiplier" numeric(5,2) NOT NULL DEFAULT 1.5,
    "MaxOvertimeHoursPerMonth" integer NOT NULL DEFAULT 40,
    "UnpaidLeaveDayMultiplier" numeric(5,2) NOT NULL DEFAULT 1,
    "WorkDaysPerMonth" integer NOT NULL DEFAULT 26,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_SalaryPolicies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SalaryPolicies_Companies_CompanyId" FOREIGN KEY ("CompanyId")
        REFERENCES "Companies" ("Id") ON DELETE RESTRICT
);

-- 3) Create index (idempotent)
CREATE INDEX IF NOT EXISTS "IX_SalaryPolicies_CompanyId" ON "SalaryPolicies" ("CompanyId");

-- 4) Register migration in EF history
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260221232431_AddSalaryPolicyAndAttendanceDetails', '9.0.0'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221232431_AddSalaryPolicyAndAttendanceDetails'
);

-- 5) Set table ownership
ALTER TABLE IF EXISTS "SalaryPolicies" OWNER TO sadara_user;

COMMIT;

SELECT 'Migration AddSalaryPolicyAndAttendanceDetails applied successfully!' AS result;
