CREATE TABLE IF NOT EXISTS "WorkCenters" (
    "Id" SERIAL PRIMARY KEY,
    "Name" TEXT NOT NULL DEFAULT '',
    "Description" TEXT,
    "Latitude" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "Longitude" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "RadiusMeters" DOUBLE PRECISION NOT NULL DEFAULT 200,
    "CompanyId" UUID,
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMP WITH TIME ZONE,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "DeletedAt" TIMESTAMP WITH TIME ZONE,
    CONSTRAINT "FK_WorkCenters_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies"("Id")
);
