"""initial schema

Revision ID: 39c412c462ea
Revises: 
Create Date: 2026-07-18 05:55:01.281851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# مُعرّفات الهجرة، يستخدمها Alembic.
revision: str = '39c412c462ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarmrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alarmrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alarmrecord_olt_id'), ['olt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarmrecord_ts'), ['ts'], unique=False)

    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=True),
    sa.Column('user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditlog_olt_id'), ['olt_id'], unique=False)

    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_olt_id'), ['olt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_ts'), ['ts'], unique=False)

    op.create_table('oltdevice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reachable', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ontrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('fsp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ont_id', sa.Integer(), nullable=False),
    sa.Column('sn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('srv_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mgmt_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rx_power', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['olt_id'], ['oltdevice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ontrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ontrecord_olt_id'), ['olt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ontrecord_sn'), ['sn'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ontrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ontrecord_sn'))
        batch_op.drop_index(batch_op.f('ix_ontrecord_olt_id'))

    op.drop_table('ontrecord')
    op.drop_table('oltdevice')
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_ts'))
        batch_op.drop_index(batch_op.f('ix_metric_olt_id'))

    op.drop_table('metric')
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditlog_olt_id'))

    op.drop_table('auditlog')
    with op.batch_alter_table('alarmrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alarmrecord_ts'))
        batch_op.drop_index(batch_op.f('ix_alarmrecord_olt_id'))

    op.drop_table('alarmrecord')
    # ### end Alembic commands ###
