"""add starlink device

Revision ID: c902d37b1884
Revises: e25375b39b77
Create Date: 2026-07-20 12:49:22.251899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# مُعرّفات الهجرة، يستخدمها Alembic.
revision: str = 'c902d37b1884'
down_revision: Union[str, None] = 'e25375b39b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starlinkdevice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hardware', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kit_serial', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscriber', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('national_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('governorate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('landmark', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('electronic_house_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('property_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('starlinkdevice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_starlinkdevice_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_starlinkdevice_governorate'), ['governorate'], unique=False)
        batch_op.create_index(batch_op.f('ix_starlinkdevice_kit_serial'), ['kit_serial'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starlinkdevice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_starlinkdevice_kit_serial'))
        batch_op.drop_index(batch_op.f('ix_starlinkdevice_governorate'))
        batch_op.drop_index(batch_op.f('ix_starlinkdevice_created_at'))

    op.drop_table('starlinkdevice')
    # ### end Alembic commands ###
