"""add_config_snapshot

Revision ID: e25375b39b77
Revises: cdcf9212050f
Create Date: 2026-07-18 21:58:18.162570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# مُعرّفات الهجرة، يستخدمها Alembic.
revision: str = 'e25375b39b77'
down_revision: Union[str, None] = 'cdcf9212050f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configsnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['olt_id'], ['oltdevice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configsnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configsnapshot_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_configsnapshot_olt_id'), ['olt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configsnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configsnapshot_olt_id'))
        batch_op.drop_index(batch_op.f('ix_configsnapshot_created_at'))

    op.drop_table('configsnapshot')
    # ### end Alembic commands ###
