-- ==================== Inventory System Tables ====================
-- Run on: sadara_db @ 72.61.183.61

CREATE TABLE IF NOT EXISTS "InventoryCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "NameEn" character varying(200),
    "ParentCategoryId" integer,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_InventoryCategories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InventoryCategories_Companies" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InventoryCategories_Parent" FOREIGN KEY ("ParentCategoryId") REFERENCES "InventoryCategories" ("Id") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_InventoryCategories_CompanyId" ON "InventoryCategories" ("CompanyId");

CREATE TABLE IF NOT EXISTS "Suppliers" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "Name" character varying(200) NOT NULL,
    "ContactPerson" character varying(100),
    "Phone" character varying(20),
    "Email" character varying(100),
    "Address" character varying(500),
    "TaxNumber" character varying(50),
    "Notes" text,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Suppliers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Suppliers_Companies" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_Suppliers_CompanyId" ON "Suppliers" ("CompanyId");

CREATE TABLE IF NOT EXISTS "Warehouses" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "Name" character varying(200) NOT NULL,
    "Code" character varying(50),
    "Address" character varying(500),
    "Description" character varying(500),
    "IsActive" boolean NOT NULL DEFAULT true,
    "IsDefault" boolean NOT NULL DEFAULT false,
    "ManagerUserId" uuid,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Warehouses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Warehouses_Companies" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Warehouses_Users" FOREIGN KEY ("ManagerUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "IX_Warehouses_CompanyId" ON "Warehouses" ("CompanyId");

CREATE TABLE IF NOT EXISTS "InventoryItems" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "Name" character varying(200) NOT NULL,
    "NameEn" character varying(200),
    "SKU" character varying(50) NOT NULL,
    "Barcode" character varying(100),
    "Description" character varying(500),
    "CategoryId" integer,
    "Unit" integer NOT NULL DEFAULT 0,
    "CostPrice" numeric(18,2) NOT NULL DEFAULT 0,
    "SellingPrice" numeric(18,2),
    "MinStockLevel" integer NOT NULL DEFAULT 0,
    "MaxStockLevel" integer NOT NULL DEFAULT 0,
    "ImageUrl" character varying(500),
    "IsActive" boolean NOT NULL DEFAULT true,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_InventoryItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InventoryItems_Companies" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InventoryItems_Categories" FOREIGN KEY ("CategoryId") REFERENCES "InventoryCategories" ("Id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "IX_InventoryItems_CompanyId" ON "InventoryItems" ("CompanyId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_InventoryItems_CompanyId_SKU" ON "InventoryItems" ("CompanyId", "SKU");

CREATE TABLE IF NOT EXISTS "PurchaseOrders" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "OrderNumber" character varying(50) NOT NULL,
    "SupplierId" uuid NOT NULL,
    "WarehouseId" uuid NOT NULL,
    "OrderDate" timestamp with time zone NOT NULL DEFAULT now(),
    "ExpectedDeliveryDate" timestamp with time zone,
    "ReceivedDate" timestamp with time zone,
    "Status" integer NOT NULL DEFAULT 0,
    "TotalAmount" numeric(18,2) NOT NULL DEFAULT 0,
    "DiscountAmount" numeric(18,2),
    "TaxAmount" numeric(18,2),
    "NetAmount" numeric(18,2) NOT NULL DEFAULT 0,
    "Notes" text,
    "AttachmentUrl" character varying(500),
    "CreatedById" uuid NOT NULL,
    "ApprovedById" uuid,
    "JournalEntryId" uuid,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_PurchaseOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PO_Suppliers" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PO_Warehouses" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PO_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PO_ApprovedBy" FOREIGN KEY ("ApprovedById") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_PO_JournalEntry" FOREIGN KEY ("JournalEntryId") REFERENCES "JournalEntries" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_PO_Companies" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_PO_CompanyId_OrderNumber" ON "PurchaseOrders" ("CompanyId", "OrderNumber");
CREATE INDEX IF NOT EXISTS "IX_PO_SupplierId" ON "PurchaseOrders" ("SupplierId");
CREATE INDEX IF NOT EXISTS "IX_PO_Status" ON "PurchaseOrders" ("Status");

CREATE TABLE IF NOT EXISTS "PurchaseOrderItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PurchaseOrderId" uuid NOT NULL,
    "InventoryItemId" uuid NOT NULL,
    "Quantity" integer NOT NULL DEFAULT 0,
    "ReceivedQuantity" integer NOT NULL DEFAULT 0,
    "UnitPrice" numeric(18,2) NOT NULL DEFAULT 0,
    "TotalPrice" numeric(18,2) NOT NULL DEFAULT 0,
    "Notes" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_PurchaseOrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_POI_PurchaseOrder" FOREIGN KEY ("PurchaseOrderId") REFERENCES "PurchaseOrders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_POI_InventoryItem" FOREIGN KEY ("InventoryItemId") REFERENCES "InventoryItems" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "SalesOrders" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "OrderNumber" character varying(50) NOT NULL,
    "CustomerName" character varying(200),
    "CustomerPhone" character varying(20),
    "WarehouseId" uuid NOT NULL,
    "OrderDate" timestamp with time zone NOT NULL DEFAULT now(),
    "Status" integer NOT NULL DEFAULT 0,
    "TotalAmount" numeric(18,2) NOT NULL DEFAULT 0,
    "DiscountAmount" numeric(18,2),
    "TaxAmount" numeric(18,2),
    "NetAmount" numeric(18,2) NOT NULL DEFAULT 0,
    "PaymentMethod" integer NOT NULL DEFAULT 0,
    "Notes" text,
    "CreatedById" uuid NOT NULL,
    "JournalEntryId" uuid,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_SalesOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SO_Warehouses" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SO_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SO_JournalEntry" FOREIGN KEY ("JournalEntryId") REFERENCES "JournalEntries" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_SO_Companies" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_SO_CompanyId_OrderNumber" ON "SalesOrders" ("CompanyId", "OrderNumber");
CREATE INDEX IF NOT EXISTS "IX_SO_Status" ON "SalesOrders" ("Status");

CREATE TABLE IF NOT EXISTS "SalesOrderItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SalesOrderId" uuid NOT NULL,
    "InventoryItemId" uuid NOT NULL,
    "Quantity" integer NOT NULL DEFAULT 0,
    "UnitPrice" numeric(18,2) NOT NULL DEFAULT 0,
    "TotalPrice" numeric(18,2) NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_SalesOrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SOI_SalesOrder" FOREIGN KEY ("SalesOrderId") REFERENCES "SalesOrders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SOI_InventoryItem" FOREIGN KEY ("InventoryItemId") REFERENCES "InventoryItems" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "TechnicianDispensings" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "VoucherNumber" character varying(50) NOT NULL,
    "TechnicianId" uuid NOT NULL,
    "WarehouseId" uuid NOT NULL,
    "ServiceRequestId" uuid,
    "DispensingDate" timestamp with time zone NOT NULL DEFAULT now(),
    "Status" integer NOT NULL DEFAULT 0,
    "Type" integer NOT NULL DEFAULT 0,
    "Notes" text,
    "CreatedById" uuid NOT NULL,
    "ApprovedById" uuid,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_TechnicianDispensings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TD_Technician" FOREIGN KEY ("TechnicianId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TD_Warehouse" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TD_ServiceRequest" FOREIGN KEY ("ServiceRequestId") REFERENCES "ServiceRequests" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_TD_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TD_ApprovedBy" FOREIGN KEY ("ApprovedById") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_TD_Companies" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_TD_CompanyId_VoucherNumber" ON "TechnicianDispensings" ("CompanyId", "VoucherNumber");
CREATE INDEX IF NOT EXISTS "IX_TD_TechnicianId" ON "TechnicianDispensings" ("TechnicianId");
CREATE INDEX IF NOT EXISTS "IX_TD_Status" ON "TechnicianDispensings" ("Status");

CREATE TABLE IF NOT EXISTS "TechnicianDispensingItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TechnicianDispensingId" uuid NOT NULL,
    "InventoryItemId" uuid NOT NULL,
    "Quantity" integer NOT NULL DEFAULT 0,
    "ReturnedQuantity" integer NOT NULL DEFAULT 0,
    "Notes" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_TechnicianDispensingItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TDI_Dispensing" FOREIGN KEY ("TechnicianDispensingId") REFERENCES "TechnicianDispensings" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TDI_InventoryItem" FOREIGN KEY ("InventoryItemId") REFERENCES "InventoryItems" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "StockMovements" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "InventoryItemId" uuid NOT NULL,
    "WarehouseId" uuid NOT NULL,
    "MovementType" integer NOT NULL DEFAULT 0,
    "Quantity" integer NOT NULL DEFAULT 0,
    "StockBefore" integer NOT NULL DEFAULT 0,
    "StockAfter" integer NOT NULL DEFAULT 0,
    "UnitCost" numeric(18,2),
    "ReferenceType" character varying(50),
    "ReferenceId" character varying(100),
    "ReferenceNumber" character varying(50),
    "Description" character varying(500),
    "CreatedById" uuid NOT NULL,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_StockMovements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SM_InventoryItem" FOREIGN KEY ("InventoryItemId") REFERENCES "InventoryItems" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SM_Warehouse" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SM_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SM_Companies" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_SM_CompanyId" ON "StockMovements" ("CompanyId");
CREATE INDEX IF NOT EXISTS "IX_SM_ItemWarehouseDate" ON "StockMovements" ("InventoryItemId", "WarehouseId", "CreatedAt");

CREATE TABLE IF NOT EXISTS "WarehouseStocks" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WarehouseId" uuid NOT NULL,
    "InventoryItemId" uuid NOT NULL,
    "CurrentQuantity" integer NOT NULL DEFAULT 0,
    "ReservedQuantity" integer NOT NULL DEFAULT 0,
    "AverageCost" numeric(18,2) NOT NULL DEFAULT 0,
    "LastStockInDate" timestamp with time zone,
    "LastStockOutDate" timestamp with time zone,
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_WarehouseStocks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WS_Warehouse" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WS_InventoryItem" FOREIGN KEY ("InventoryItemId") REFERENCES "InventoryItems" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WS_Companies" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_WS_WarehouseId_InventoryItemId" ON "WarehouseStocks" ("WarehouseId", "InventoryItemId");
CREATE INDEX IF NOT EXISTS "IX_WS_CompanyId" ON "WarehouseStocks" ("CompanyId");
